### PR TITLE
Replace static mutex

### PR DESCRIPTION
**Pull request by ramn**
So that we can compile on stable rust

### CODE REVIEW

**Comment by ramn** [comment]
When I run the tests on my machine, they all succeed.

**Comment by dginev** [comment]
Btw a good idea is to start using *both* stable and nightly on Travis from this PR on, and possibly even beta. After all the core idea is to make the crate work on more rust releases, rather than less.

**Comment by dginev** [comment]
And the 3 projects I am involved with that use this crate are all based on the nightly toolchain, so breaking that here would be a no-go.

**Comment by ramn** [comment]
What should I put in the travis file?

**Comment by dginev** [comment]
Based on the [travis docs](https://docs.travis-ci.com/user/languages/rust) I'd suggest:
```
language: rust
rust:
  - stable
  - beta
  - nightly
```

**Comment by ramn** [comment]
Thanks, I'll try that.

**Comment by ramn** [comment]
Strange, works on 1.8 nightly on macos

**Comment by dginev** [comment]
The joys of travis. I'll take a look a bit later today if you don't find an obvious cause for the travis failure.

**Comment by ramn** [comment]
Can we set RUST_BACKTRACE=1 ?

**Comment by dginev** [comment]
I just installed today's nightly and it broke not only your PR but also the main rust-libxml master. So not a problem for your PR, we should fix it in master first.

**Comment by dginev** [comment]
FYI it seems that xmlReadFile and htmlReadFile are now returning null pointers in the test suite.

**Comment by dginev** [comment]
@ramn I merged a fix that brings us up to date with the current nightly, would you care to rebase the PR on the latest master? I'll look into it then (Travis should pass)

**Comment by ramn** [comment]
Rebased https://github.com/jfschaefer/rust-libxml/pull/5

**Pull request closed without merging**
